<h2>原文：<a href="https://codeinchinese.com/2019/02/18/%E6%89%A9%E5%B1%95Python%E6%8E%A7%E5%88%B6%E5%8F%B0%E5%AE%9E%E7%8E%B0%E4%B8%AD%E6%96%87%E5%8F%8D%E9%A6%88%E4%BF%A1%E6%81%AF%E4%B9%8B%E4%BA%8C-%E6%AD%A3%E5%88%99%E6%9B%BF%E6%8D%A2.markdown">扩展Python控制台实现中文反馈信息之二-正则替换</a></h2>
<hr/>
<h2>layout: post
comments: true
title:  扩展Python控制台实现中文反馈信息之二-正则替换
description: 扩展默认的Python控制台, 通过正则匹配和替换, 将报错/警告等信息翻译成中文.
date:   2019-02-18 00:00:00 -0700
categories: 语言设计</h2>
<p>"中文编程"知乎专栏<a href="https://zhuanlan.zhihu.com/p/57079638">原文地址</a></p>
<p>![2019-02-18-python控制台扩展]({{ "/assets/2019-02-18-python控制台扩展.png" | absolute_url }})</p>
<p>续前文<a href="https://zhuanlan.zhihu.com/p/56411693">扩展Python控制台实现中文反馈信息</a>, 实现了如下效果:</p>
<pre><code class="language-python">&gt;&gt;&gt; 学
Traceback (most recent call last):
  File "&lt;console&gt;", line 1, in &lt;module&gt;
命名错误: 命名'学'未定义
&gt;&gt;&gt; [1] + 2
Traceback (most recent call last):
  File "&lt;console&gt;", line 1, in &lt;module&gt;
类型错误: 只能将list(而非"int")联结到list
&gt;&gt;&gt; [1].length
Traceback (most recent call last):
  File "&lt;console&gt;", line 1, in &lt;module&gt;
属性错误: 'list'个体没有'length'属性
&gt;&gt;&gt; def foo():
...     def bar():
...             print(type)
...     bar()
...     type = 1
... 
&gt;&gt;&gt; foo()
Traceback (most recent call last):
  File "&lt;console&gt;", line 1, in &lt;module&gt;
  File "&lt;console&gt;", line 4, in foo
  File "&lt;console&gt;", line 3, in bar
命名错误: 在闭合作用域中, 自由变量'type'在引用之前未被赋值
</code></pre>
<p>源码在: <a href="https://github.com/program-in-chinese/study/tree/6084cbfc39166842b95d25d5c2fe419f1c604475/1-%E5%9F%BA%E7%A1%80/%E6%8E%A7%E5%88%B6%E5%8F%B0">program-in-chinese/study</a> 现在支持的报错信息列表见测试用例: <a href="https://github.com/program-in-chinese/study/blob/6084cbfc39166842b95d25d5c2fe419f1c604475/1-%E5%9F%BA%E7%A1%80/%E6%8E%A7%E5%88%B6%E5%8F%B0/test%E7%BF%BB%E8%AF%91.py">test翻译.py</a></p>
<p>参考<a href="https://docs.python.org/3/library/re.html#re.sub">re - Regular expression operations - Python 3.7.2 documentation</a>, 用一系列(现8个)正则表达式匹配和替换实现, 比如:</p>
<pre><code class="language-python">if re.match(r"NameError: name '(.*)' is not defined", 原始信息):
    return re.sub(r"NameError: name '(.*)' is not defined", r"命名错误: 命名'\1'未定义", 原始信息)
</code></pre>
<p>期间发现Python编译器源代码中的报错信息所处位置比较分散, 似乎有上百处. 下面的打算:</p>
<ul>
<li>首先将它打包发布到Pypi, 参考<a href="https://packaging.python.org/tutorials/packaging-projects/">Packaging Python Projects</a></li>
<li>逐步补充报错信息, 除了在自己使用过程中发现的新报错信息, 也可调研哪些报错最为常见</li>
<li>逐步改进中文信息. 比如<code>只能将list(而非"int")联结到list</code> =&gt; <code>只能将列表(而非整数)联结到列表</code></li>
<li>上文提到的通过"定制sys.excepthook"实现尚未研究. 如无明显优势, 打算置后.</li>
</ul>
